; 
; PlatformIO Project Configuration File
;
; Default Env: C3_mini 
; (Build note: be sure (a soft link) libOverseer is in lib/libOverseer)


[platformio]
default_envs = esp32-c3-devkitm_serial
build_dir = ~/temp/build
src_dir = c3__mini/src
include_dir = c3__mini/include
lib_dir = c3__mini/lib
; test_dir = c3__mini/test/core

[env]
lib_deps = 
	adafruit/Adafruit AHTX0@^2.0.5
	https://github.com/me-no-dev/AsyncTCP.git
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	bblanchon/ArduinoJson@^7.1.0
lib_extra_dirs = 	
	../libOverseer
build_src_filter = 
	+<*>
	-<*test*>
build_unflags = -std=gnu++11
build_type = debug

[env:esp32-c3-devkitm_serial]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = boards/esp32-c3-partitions.csv
debug_tool = esp-builtin
debug_init_break = tbreak setup
debug_speed = 2000
debug_load_mode = modified
monitor_speed = 115200
build_flags = 
	-D BOARD_ESP32C3
	-D OVERSEER_TARGET_PLATFORM=ESP32_C3_MINI	
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-std=gnu++2a
	-I c3__mini/lib

[env:esp32-c3-devkitm_ota]
extends = env:esp32-c3-devkitm_serial
upload_protocol = espota
upload_port = 192.168.1.50
build_flags = 
	-D BOARD_ESP32C3
	-D OVERSEER_TARGET_PLATFORM=ESP32_C3_MINI	
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-std=gnu++2a
	-I c3__mini/lib



[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-n16r8
framework = arduino
debug_tool = esp-builtin
debug_init_break = tbreak setup
debug_speed = 2000
debug_load_mode = modified
monitor_speed = 115200
build_flags =
	-D BOARD_ESP32S3
	-I c3__mini/lib


[env:native_test]
platform = native
test_build_src = no
lib_ignore =
	src
	libOverseer
lib_deps =
	https://github.com/boost-ext/ut.git
	bblanchon/ArduinoJson@^7.1.0
build_flags =
	-std=gnu++20
	-D BOARD_ESP32C3
	-I lib/libOverseer/src
	-I test/mocks
	-I c3__mini/lib
