; 
; PlatformIO Project Configuration File
;
; Default Env: C3_mini 
; (Build note: be sure (a soft link) libOverseer is in lib/libOverseer)


[platformio]
default_envs = esp32-c3-devkitm_serial
build_dir = ~/temp/build
src_dir = c3__mini/src
include_dir = c3__mini/include
; test_dir = c3__mini/test/core

[env]
lib_deps = 
	adafruit/Adafruit AHTX0@^2.0.5
	https://github.com/me-no-dev/AsyncTCP.git
	https://github.com/me-no-dev/ESPAsyncWebServer.git
lib_extra_dirs = 	
	../libOverseer
build_src_filter = 
	+<*>
	-<*test*>
	-<src/device/environment/>
	-<*libOverseer/src/device/environment/>
build_flags = 
	-D OVERSEER_TARGET_PLATFORM=ESP32_C3_MINI
build_unflags = -std=gnu++11
build_type = debug

[env:esp32-c3-devkitm_serial]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = esp32-c3-partitions.csv
debug_tool = esp-builtin
debug_init_break = tbreak setup
debug_speed = 2000
debug_load_mode = modified
monitor_speed = 115200
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-c3-devkitm_ota]
extends = env:esp32-c3-devkitm_serial
upload_protocol = espota
upload_port = 192.168.1.50

[env:native_test]
platform = native
test_build_src = no
lib_ignore =
	src
	libOverseer
lib_deps =
	https://github.com/boost-ext/ut.git
build_flags =
	-std=gnu++20
	-I lib/libOverseer/src
	-I test/mocks
